### PR TITLE
Cpan Steup

### PR DESCRIPTION
**Pull request by angerhang**
Here we have a more complete `README` and the configuration files for `cpan` submission. 
For tickets: #74 #73.

### CODE REVIEW

**Comment by kohlhase** [comment]
this looks good, even though someone should go over the README.md for language polishing. Why is test.pm deleted?

**Comment by angerhang** [comment]
Because we never need it. I added Test.pm for the old way of testing and forgot to delete it :-)

**Comment by kohlhase** [comment]
merged, do you want to delete the cpan branch?

**Comment by angerhang** [comment]
Yes we just have to keep in mind that whenever we add or delete any files in the future, we also change the `MANIFEST` accordingly. `MANIFEST` is essentially a list of files that we have.

**Pull request merged**
