### PR TITLE
Testcase

### PR DESCRIPTION
**Pull request by angerhang**
See #11 for details.

### CODE REVIEW

**Comment by kohlhase** [comment]
the CI tests have not completed, you should investigate that before you merge. If you need help @cmaeder knows more.

**Comment by angerhang** [comment]
I think in the travis test `cpanm .` is not installing the sTeX plugin into the right place. In this https://travis-ci.org/KWARC/LaTeXML-Plugin-sTeX/builds/114946820, last bits we `ls` all the LaTeXML bindings but no sTeX binding is shown. @cmaeder what do you think?

**Comment by angerhang** [comment]
Apparently my last comment doesn't make sense since if `cpanm .`fails to install, the bindings will exist in the LaTeXML/package directory. I should have check it with the `-notest` option being turned on. Will investigate more.

**Comment by cmaeder** [comment]
The file `smglom.cls` is missing which is part of https://github.com/KWARC/sTeX.git that is currently not installed!

**Comment by cmaeder** [comment]
@angerhang I discovered that the tests go through only after the package has been successfully installed without the tests! The installations adds a file `~/perl5/lib/perl5/sTeXTest.pm` and I've no idea where this name comes from.

**Comment by cmaeder** [comment]
It seems the yet uninstalled `smglom.cls.ltxml` (from the plugin) can not be found by `LaTeX.pool.ltxml` that was installed by `LaTeXML`.

**Comment by angerhang** [comment]
Why `smglom.cls.ltxml` cannot be found?

Where did this problem occur?

**Comment by cmaeder** [comment]
Furthermore the profile `stex-smglom` in the two failing test does not exist (and can be omitted instead). If I change the profile to `stex-smglom-module` it fails for `calbf.sty.ltxml` and `lstomdoc.sty.ltxml`.

**Comment by cmaeder** [comment]
> Why smglom.cls.ltxml cannot be found?

Somehow the searchpath given is not respected.

**Comment by angerhang** [comment]
`sTeXTest.pm` is the test module that I was using before and in fact we don't actually need it. Going to delete it.

**Pull request merged**
